name = "CFL3DPost"
uuid = "2b812ebb-c471-42a3-b65b-7d68d1b150ff"
authors = ["XUE Cheng <xuecheng@nuaa.edu.cn> and contributors"]
version = "0.1.0"

[deps]
Formatting = "59287772-0a20-5a39-b81b-1366585eb4c0"
FortranFiles = "c58ffaec-ab22-586d-bfc5-781a99fd0b10"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"

[compat]
julia = "1.6"
Formatting = "0.4"
FortranFiles = "0.6"
Parameters = "0.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
